-- Consumer contracts make a new palette fail during construction instead of
-- leaving one application half themed after deployment.
return {
    starship = {
        "palette.fg0",
        "palette.bg1",
        "palette.bg3",
        "palette.blue_bright",
        "palette.aqua_bright",
        "palette.green_bright",
        "palette.orange_bright",
        "palette.purple_bright",
        "palette.red_bright",
        "palette.yellow_bright",
    },
    wezterm = {
        "ui.background",
        "ui.foreground",
        "ui.cursor",
        "ansi.black",
        "ansi.bright_white",
    },
    yazi = {
        "ui.background",
        "ui.foreground",
        "ui.surface",
        "palette.blue_bright",
        "palette.aqua_bright",
        "palette.green_bright",
        "palette.orange",
        "palette.purple_bright",
        "palette.red_bright",
        "palette.yellow_bright",
    },
    zsh = {
        "ui.border_subtle",
        "ui.foreground",
        "palette.fg0",
        "palette.fg1",
        "palette.blue_bright",
        "palette.aqua_bright",
        "palette.orange_bright",
        "palette.yellow_bright",
    },
    fastfetch = {
        "ansi.bright_black",
        "palette.orange_bright",
    },
    tmux = {
        "ui.background",
        "ui.border_subtle",
        "palette.bg1",
        "palette.bg2",
        "palette.bg3",
        "palette.blue",
        "palette.blue_bright",
        "palette.aqua",
        "palette.fg1",
        "palette.fg2",
        "palette.fg3",
        "palette.green",
        "palette.orange",
        "palette.orange_bright",
        "palette.red_bright",
        "palette.yellow",
        "palette.yellow_bright",
    },
}
